In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('LLCP2020.csv')

In [3]:
df.shape

(401958, 279)

In [4]:
pd.set_option('display.max_columns', 500)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHONE,LADULT1,COLGSEX,NUMADULT,LANDSEX,NUMMEN,NUMWOMEN,RESPSLCT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,EXERANY2,SLEPTIM1,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD2,HAVARTH4,ADDEPEV3,CHCKDNY2,DIABETE4,DIABAGE3,LASTDEN4,RMVTETH4,MARITAL,EDUCA,RENTHOM1,NUMHHOL3,NUMPHON3,CPDEMO1B,VETERAN3,EMPLOY1,CHILDREN,INCOME2,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,SHINGLE2,PNEUVAC4,FALL12MN,FALLINJ4,SEATBELT,DRNKDRI2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PCPSAAD3,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,COLNSCPY,COLNTEST,SIGMSCPY,SIGMTEST,BLDSTOL1,LSTBLDS4,STOOLDNA,SDNATEST,VIRCOLON,VCLNTEST,HIVTST7,HIVTSTD3,HIVRISK5,PDIABTST,PREDIAB1,INSULIN1,BLDSUGAR,FEETCHK3,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM1,DIABEYE,DIABEDU,TOLDCFS,HAVECFS,WORKCFS,TOLDHEPC,TRETHEPC,PRIRHEPC,HAVEHEPC,HAVEHEPB,MEDSHEPB,HLTHCVR1,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,ECIGARET,ECIGNOW,MARIJAN1,USEMRJN2,RSNMRJN1,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSCN,CNCRDIFF,CNCRAGE,CNCRTYP1,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,PCPSADE1,PCDMDEC1,HPVADVC4,HPVADSHT,TETANUS1,IMFVPLA1,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HCVU651,_TOTINDA,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_EXTETH3,_ALTETH3,_DENVST3,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWK1,_RFDRHV7,_FLSHOT7,_PNEUMO3,_RFSEAT2,_RFSEAT3,_DRNKDRV,_RFMAM22,_MAM5023,_RFPAP35,_RFPSA23,_CLNSCPY,_SGMSCPY,_SGMS10Y,_RFBLDS4,_STOLDNA,_VIRCOLN,_SBONTIM,_CRCREC1,_AIDTST4
0,1.0,1.0,b'01042020',b'01',b'04',b'2020',1100.0,b'2020000001',2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,30.0,3.0,2.0,3.0,1.0,4.0,1.0,5.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,35.0,1.0,2.0,2.0,6.0,1.0,2.0,NaN,1.0,2.0,4.0,88.0,1.0,NaN,106.0,507.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,1.0,3.0,1.0,4.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0,21994.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,7.0,2.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,1.0,NaN,NaN,NaN,NaN,1.0,0.465411,460.002849,284.335672,1.0,2.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,67.0,170.0,4808.0,1660.0,1.0,1.0,1.0,4.0,1.0,1.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,1.0,1.0,9.0,2.0,2.0,NaN,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0
1,1.0,1.0,b'02072020',b'02',b'07',b'2020',1200.0,b'2020000002',2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,1.0,7.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,NaN,1.0,1.0,3.0,6.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,99.0,NaN,170.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,2.0,NaN,NaN,NaN,NaN,1.0,0.465411,460.002849,171.283329,1.0,1.0,1.0,9.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,65.0,6.0,64.0,163.0,7711.0,2918.0,3.0,2.0,1.0,4.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,9.990000e+04,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
2,1.0,1.0,b'01232020',b'01',b'23',b'2020',1100.0,b'2020000003',2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,7.0,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,7777.0,508.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,2.0,2.0,88.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11012.0,279.748901,1.0,279.748901,2.0,NaN,NaN,NaN,NaN,1.0,0.465411,1847.859106,1334.368863,1.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,3.0,1.0,9.0,9.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,65.0,6.0,68.0,173.0,NaN,NaN,NaN,9.0,1.0,3.0,5.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,1.0,1.0,9.0,1.0,1.0,1.0,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0
3,1.0,1.0,b'01092020',b'01',b'09',b'2020',1100.0,b'2020000004',2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,2.0,6.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,1.0,3.0,4.0,1.0,9.0,NaN,9.0,2.0,5.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,2.0,NaN,1.0,7.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,1.0,NaN,NaN,NaN,NaN,9.0,NaN,1472.417322,1297.486618,1.0,1.0,1.0,9.0,2.0,2.0,1.0,1.0,3.0,2.0,2.0,1.0,9.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0,2.0,9.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,1.0,1.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,1.0,1.0,b'01042020',b'01',b'04',b'2020',1100.0,b'2020000005',2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,8.0,3.0,6.0,2.0,2.0,NaN,8.0,2.0,7.0,88.0,77.0,NaN,126.0,506.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,1.0,1.0,88.0,NaN,1.0,NaN,1.0,1.0,2.0,NaN,7.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0,2.0,NaN,7.0,NaN,7.0,NaN,2.0,NaN,7.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,1.0,NaN,NaN,NaN,NaN,9.0,NaN,1472.417322,454.815127,1.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,9.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,66.0,168.0,5715.0,2034.0,2.0,1.0,1.0,4.0,9.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,9.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

## Selected Attributes

### Response Variables:
1. **DIABETE4**:   (Ever told) (you had) diabetes?  (If Yes -  and respondent is female, ask Was this only when you were pregnant? If Respondent says pre-diabetes or borderline diabetes, use response code 4.)

### Predictor Variables:

#### High Blood Pressure

#### High Cholesterol

#### BMI
5. **_BMI5**: Body Mass Index (BMI)

#### Smoking
6. **SMOKE100**: Have you smoked at least 100 cigarettes in your entire life?   [Note:  5 packs = 100 cigarettes]

#### Other Chronic Health Conditions
7. **CVDSTRK3**: (Ever told) (you had) a stroke.
8. **_MICHD**: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)

#### Physical Activity
9.  **_TOTINDA**: Adults who reported doing physical activity or exercise during the past 30 days other than their regular job

#### Diet


#### Alcohol Consumption
10. **_RFDRHV8**: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week)

#### Health Care
11. **_HLTHPLN**: Adults who had some form of health insurance
12. **MEDCOST1**: Was there a time in the past 12 months when you needed to see a doctor but could not because you could not afford it?

#### Health General and Mental Health
13. **GENHLTH**: Would you say that in general your health is excellent, very good, good, fair, or poor?
14. **MENTHLTH**: Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?
15. **PHYSHLTH**: Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?
16. **DIFFWALK**: Do you have serious difficulty walking or climbing stairs?

#### Demographic Variables
17. **SEXVAR**: Sex of Respondent
18. **_AGEG5YR**: Fourteen-level age category
19. **EDUCA**: What is the highest grade or year of school you completed?
20. **INCOME3**: Is your annual household income from all sources: (If respondent refuses at any income level, code "Refused.")

In [5]:
brfss_df_selected = df[['DIABETE4',
                                         '_BMI5', 
                                         'SMOKE100', 
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_RFDRHV7', 
                                         'MEDCOST', 
                                         'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', 
                                         'SEXVAR', '_AGEG5YR', 'EDUCA', 'INCOME2' ]]

In [6]:
brfss_df_selected.shape

(401958, 16)

In [7]:
brfss_df_selected.head()

,DIABETE4,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV7,MEDCOST,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME2
0,1.0,1660.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,30.0,3.0,2.0,2.0,8.0,6.0,1.0
1,3.0,2918.0,NaN,2.0,2.0,1.0,9.0,1.0,3.0,88.0,88.0,2.0,2.0,10.0,6.0,99.0
2,3.0,NaN,2.0,2.0,2.0,1.0,1.0,2.0,3.0,88.0,88.0,2.0,2.0,10.0,5.0,7.0
3,3.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0,88.0,88.0,2.0,2.0,13.0,4.0,99.0
4,3.0,2034.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,88.0,88.0,2.0,2.0,13.0,6.0,77.0

In [8]:
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(352193, 16)

## Clean

In [9]:
# DIABETE4 = Diabetes Awareness
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({2:0, 3:0, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 9]
brfss_df_selected.DIABETE4.unique()

array([1., 0.])

In [10]:
# #1 _RFHYPE6 = High Blood Pressure Awareness
# #Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
# brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
# brfss_df_selected._RFHYPE6.unique()

In [11]:
# # TOLDHI3 = Cholesterol Awareness
# # Change 2 to 0 because it is No
# # Remove all 7 (dont knows)
# # Remove all 9 (refused)
# brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
# brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
# brfss_df_selected.TOLDHI3.unique()

In [12]:
# # _CHOLCH3 = Cholesterol check within past five years
# # Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# # Remove 9 (don't know/refused)
# brfss_df_selected['_CHOLCH3'] = brfss_df_selected['_CHOLCH3'].replace({3:0,2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._CHOLCH3 != 9]
# brfss_df_selected._CHOLCH3.unique()

In [13]:
# _BMI5 = Body mass index
# BMI are * 100
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([17., 20., 27., 24., 29., 22., 32., 26., 41., 34., 28., 23., 30.,
       18., 21., 25., 37., 31., 45., 19., 39., 33., 47., 40., 35., 44.,
       36., 59., 38., 43., 49., 42., 53., 52., 15., 51., 55., 50., 56.,
       76., 16., 57., 48., 46., 82., 12., 14., 60., 67., 63., 66., 54.,
       64., 13., 58., 62., 83., 81., 68., 61., 69., 73., 72., 79., 71.,
       75., 77., 70., 87., 80., 84., 65., 78., 86., 85., 74., 93., 94.,
       92., 95., 90., 89., 88.])

In [14]:
# SMOKE100 = Smoked at Least 100 Cigarettes
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([1., 0.])

In [15]:
# CVDSTRK3 = Chronic Health Conditions
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [16]:
# _MICHD = Ever had CHD or MI
# Coronary Heart Disease (CHD) and Myocardial Infarction (MI)
# Change 2 to 0 because this means they did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [17]:
# _TOTINDA = Leisure Time Physical Activity
# Change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([1., 0.])

In [18]:
# # _FRTLT1A = Consume Fruit 1 or more per day
# # Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_FRTLT1A'] = brfss_df_selected['_FRTLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1A != 9]
# brfss_df_selected._FRTLT1A.unique()

In [19]:
# # _VEGLT1A = Consume Vegetables 1 or more per day
# # Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_VEGLT1A'] = brfss_df_selected['_VEGLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1A != 9]
# brfss_df_selected._VEGLT1A.unique()

In [20]:
# _RFDRHV8 = Heavy Alcohol Consumption
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# Remove all 9 (don't know/refused)
brfss_df_selected['_RFDRHV7'] = brfss_df_selected['_RFDRHV7'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV7 != 9]
brfss_df_selected._RFDRHV7.unique()

array([0., 1.])

In [21]:
# _HLTHPLN = Have any health insurance
# Change 2 to 0 for no health insurance
# Remove all 9 (don't know/refused)
# brfss_df_selected['_HLTHPLN'] = brfss_df_selected['_HLTHPLN'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 7]
# brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 9]
# brfss_df_selected._HLTHPLN.unique()

In [22]:
# MEDCOST1 = Could Not Afford To See Doctor
# Change 2 to 0 for no
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['MEDCOST'] = brfss_df_selected['MEDCOST'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST != 9]
brfss_df_selected.MEDCOST.unique()

array([1., 0.])

In [23]:
# GENHLTH = General Health
# 1 is Excellent -> 5 is Poor
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([2., 4., 3., 5., 1.])

In [24]:
# MENTHLTH = Number of Days Mental Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad mental health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([30.,  0.,  2.,  5., 15.,  8.,  4.,  3., 10., 14., 20.,  1.,  7.,
       24.,  9., 25., 28., 16., 12.,  6., 17., 18., 21., 29., 22., 13.,
       23., 27., 26., 11., 19.])

In [25]:
# PHYSHLTH = Number of Days Physical Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad physical health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([ 3.,  0., 20., 28.,  6., 15.,  5., 30.,  7.,  1.,  2., 21.,  4.,
       10., 14., 18.,  8., 25., 16., 22., 29., 27., 17., 24., 12., 23.,
       26., 19.,  9., 13., 11.])

In [26]:
# DIFFWALK = Difficulty Walking or Climbing Stairs
# Change 2 to 0 for no.
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([0., 1.])

In [27]:
# SEXVAR = Respondent Sex
# Men are at higher risk for heart disease
# Change 2 to 0 (female as 0)
brfss_df_selected['SEXVAR'] = brfss_df_selected['SEXVAR'].replace({2:0})
brfss_df_selected.SEXVAR.unique()

array([0., 1.])

In [28]:
# _AGEG5YR = Reported age in five-year age categories
# 5 year increments. It is already ordinal. 1 is 18-24 all the way up to 13 which is 80 and older
# Remove all 14 (don't know or missing)
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([ 8., 13., 10., 12.,  5., 11.,  9.,  7.,  6.,  1.,  4.,  2.,  3.])

In [29]:
# EDUCA = Education Level
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([6., 4., 2., 5., 3., 1.])

In [30]:
# INCOME3 = Income Level
# This is already an ordinal variable with 1 being less than $10,000 all the way up to 11 being $200,000 or more
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 99]
brfss_df_selected.INCOME2.unique()

array([1., 5., 6., 7., 4., 2., 8., 3.])

In [31]:
brfss_df_selected.shape

(276785, 16)

In [32]:
brfss_df_selected.head()

,DIABETE4,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV7,MEDCOST,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME2
0,1.0,17.0,1.0,0.0,0.0,1.0,0.0,1.0,2.0,30.0,3.0,0.0,0.0,8.0,6.0,1.0
5,1.0,27.0,1.0,0.0,0.0,1.0,0.0,0.0,4.0,30.0,20.0,0.0,1.0,10.0,4.0,5.0
6,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,4.0,6.0
8,0.0,24.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,28.0,1.0,0.0,5.0,6.0,6.0
10,0.0,22.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,15.0,0.0,0.0,11.0,6.0,7.0

In [33]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    235619
1.0     41166
dtype: int64

In [34]:
#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes', '_RFHYPE6':'HighBP', 'TOLDHI3':'HighChol', '_CHOLCH3':'CholCheck', '_BMI5':'BMI', 'SMOKE100':'Smoker', 'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', '_TOTINDA':'PhysActivity', '_FRTLT1A':'Fruits', '_VEGLT1A':"Veggies", '_RFDRHV7':'HvyAlcoholConsump', '_HLTHPLN':'AnyHealthcare', 'MEDCOST':'NoDocbcCost', 'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 'SEXVAR':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME2':'Income' })

In [35]:
brfss.head()

,Diabetes,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,17.0,1.0,0.0,0.0,1.0,0.0,1.0,2.0,30.0,3.0,0.0,0.0,8.0,6.0,1.0
5,1.0,27.0,1.0,0.0,0.0,1.0,0.0,0.0,4.0,30.0,20.0,0.0,1.0,10.0,4.0,5.0
6,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,4.0,6.0
8,0.0,24.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,28.0,1.0,0.0,5.0,6.0,6.0
10,0.0,22.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,15.0,0.0,0.0,11.0,6.0,7.0

In [36]:
brfss.shape

(276785, 16)

In [37]:
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    235619
1.0     41166
dtype: int64

In [38]:
brfss.to_csv('diabetes_BRFSS2020.csv', sep=",", index=False)