In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('LLCP2023.csv')

In [3]:
df.shape

(433323, 350)

In [4]:
pd.set_option('display.max_columns', 500)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,NUMADULT,RESPSLC1,LANDSEX2,LNDSXBRT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX2,CELSXBRT,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINS1,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,EXRACT12,EXEROFT1,EXERHMM1,EXRACT22,EXEROFT2,EXERHMM2,STRENGTH,BPHIGH6,BPMEDS1,CHOLCHK3,TOLDHI3,CHOLMED3,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,RENTHOM1,NUMHHOL4,NUMPHON4,CPDEMO1C,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,FALL12MN,FALLINJ5,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW2,ALCDAY4,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,PNEUVAC4,SHINGLE2,HIVTST7,HIVTSTD3,SEATBELT,DRNKDRI2,COVIDPO1,COVIDSM1,COVIDACT,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,ARTHEXER,ARTHEDU,LMTJOIN3,ARTHDIS2,JOINPAI2,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,PSATEST1,PSATIME1,PCPSARS2,PSASUGS1,PCSTALK2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,INDORTAN,NUMBURN3,SUNPRTCT,WKDAYOUT,WKENDOUT,CIMEMLO1,CDWORRY,CDDISCU1,CDHOUS1,CDSOCIA1,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,FIREARM5,GUNLOAD,LOADULK2,HASYMP1,HASYMP2,HASYMP3,HASYMP4,HASYMP5,HASYMP6,STRSYMP1,STRSYMP2,STRSYMP3,STRSYMP4,STRSYMP5,STRSYMP6,FIRSTAID,ASPIRIN,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,IMFVPLA4,HPVADVC4,HPVADSHT,TETANUS1,COVIDVA1,COVACGE1,COVIDNU2,LSATISFY,EMTSUPRT,SDLONELY,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,SDHSTRE1,RRCLASS3,RRCOGNT2,RRTREAT,RRATWRK2,RRHCARE4,RRPHYSM2,RCSGEND1,RCSXBRTH,RCSRLTN2,CASTHDX2,CASTHNO2,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPL1,_HCVU653,_TOTINDA,METVL12_,METVL22_,MAXVO21_,FC601_,ACTIN13_,ACTIN23_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC12,_MINAC22,STRFREQ_,PAMISS3_,PAMIN13_,PAMIN23_,PA3MIN_,PAVIG13_,PAVIG23_,PA3VIGM_,_PACAT3,_PAINDX3,_PA150R4,_PA300R4,_PA30023,_PASTRNG,_PAREC3,_PASTAE3,_RFHYPE6,_CHOLCH3,_RFCHOL3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4,_RFSEAT2,_RFSEAT3,_DRNKDRV
0,1.0,1.0,b'03012023',b'03',b'01',b'2023',1100.0,b'2023000001',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,3.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,57.0,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,172.0,503.0,2.0,2.0,2.0,1.0,2.0,2.0,88.0,NaN,2.0,NaN,3.0,1.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,42.791581,2.0,85.583161,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,941.163973,605.427887,1.0,1.0,1.0,1.0,9.0,2.0,NaN,NaN,1840.0,315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,63.0,160.0,7802.0,3047.0,4.0,2.0,1.0,3.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,1.0,1.0,9.0
1,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000002',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,3.0,1.0,2.0,2.0,1.0,1.0,106.0,30.0,88.0,NaN,NaN,888.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,3.0,NaN,2.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,132.0,409.0,1.0,2.0,2.0,2.0,2.0,2.0,88.0,NaN,2.0,NaN,3.0,1.0,888.0,NaN,NaN,NaN,1.0,92023.0,1.0,2.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11012.0,170.429390,1.0,170.429390,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,1874.223855,1121.992705,1.0,1.0,1.0,1.0,9.0,1.0,35.0,NaN,1803.0,309.0,2.0,NaN,30.0,NaN,6000.0,NaN,180.0,5.397605e-79,5.397605e-79,1.000000e+00,360.0,NaN,360.0,180.0,NaN,180.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,57.0,145.0,5987.0,2856.0,3.0,2.0,1.0,3.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
2,1.0,1.0,b'03082023',b'03',b'08',b'2023',1100.0,b'2023000003',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,6.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,205.0,15.0,88.0,NaN,NaN,205.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,3.0,4.0,2.0,2.0,NaN,8.0,2.0,7.0,88.0,2.0,NaN,130.0,504.0,7.0,1.0,1.0,1.0,2.0,2.0,88.0,NaN,1.0,3.0,3.0,1.0,888.0,NaN,NaN,NaN,1.0,112022.0,1.0,1.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,3.0,2.0,2.0,5.0,1.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,3.0,11011.0,42.791581,1.0,42.791581,2.0,9.0,NaN,NaN,NaN,9.0,NaN,1151.603218,600.963308,2.0,2.0,2.0,1.0,9.0,1.0,35.0,NaN,1322.0,227.0,2.0,NaN,15.0,NaN,1167.0,NaN,18.0,5.397605e-79,1.167000e+03,1.000000e+00,36.0,NaN,36.0,18.0,NaN,18.0,9.0,9.0,9.0,9.0,9.0,2.0,9.0,9.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,13.0,2.0,80.0,6.0,64.0,163.0,5897.0,2231.0,2.0,1.0,1.0,2.0,1.0,3.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
3,1.0,1.0,b'03062023',b'03',b'06',b'2023',1100.0,b'2023000004',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,88.0,88.0,3.0,1.0,2.0,3.0,1.0,1.0,103.0,30.0,88.0,NaN,NaN,888.0,3.0,NaN,3.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,2.0,1.0,2.0,1.0,3.0,NaN,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,170.0,506.0,2.0,2.0,2.0,1.0,2.0,2.0,88.0,NaN,2.0,NaN,3.0,1.0,888.0,NaN,NaN,NaN,1.0,102022.0,1.0,2.0,1.0,777777.0,1.0,NaN,2.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,2.0,1.0,2.0,11011.0,42.791581,2.0,85.583161,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,941.163973,605.427887,1.0,2.0,1.0,1.0,9.0,1.0,35.0,NaN,1914.0,328.0,2.0,NaN,30.0,NaN,3000.0,NaN,90.0,5.397605e-79,5.397605e-79,1.000000e+00,180.0,NaN,180.0,90.0,NaN,90.0,9.0,1.0,1.0,9.0,9.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,12.0,2.0,78.0,6.0,66.0,168.0,7711.0,2744.0,3.0,2.0,1.0,3.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,9.0
4,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000005',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,88.0,88.0,NaN,3.0,1.0,2.0,1.0,1.0,1.0,102.0,45.0,8.0,107.0,100.0,888.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,1.0,1.0,68.0,3.0,5.0,1.0,2.0,NaN,3.0,2.0,8.0,88.0,7.0,NaN,170.0,508.0,2.0,2.0,1.0,1.0,2.0,1.0,3.0,88.0,2.0,NaN,2.0,1.0,202.0,1.0,88.0,1.0,2.0,NaN,1.0,2.0,2.0,NaN,1.0,88.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,5.0,11011.0,42.791581,1.0,42.791581,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,470.581986,281.711042,2.0,1.0,1.0,1.0,9.0,1.0,35.0,33.0,1988.0,341.0,2.0,1.0,45.0,60.0,2000.0,7000.0,90.0,4.200000e+02,5.397605e-79,5.397605e-79,180.0,420.0,600.0,90.0,5.397605e-79,90.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,12.0,2.0,76.0,6.0,68.0,173.0,7711.0,2585.0,3.0,2.0,1.0,3.0,5.0,4.0,1.0,1.0,1.0,7.000000e+00,1.0,4.700000e+01,1.0,2.0,1.0,2.0,1.0,1.0,2.0

## Selected Attributes

### Response Variables:
1. **DIABETE4**:   (Ever told) (you had) diabetes?  (If Yes -  and respondent is female, ask Was this only when you were pregnant? If Respondent says pre-diabetes or borderline diabetes, use response code 4.)

### Predictor Variables:

#### High Blood Pressure
2. **_RFHYPE6**:  Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional

#### High Cholesterol
3. **TOLDHI3**: Have you ever been told by a doctor, nurse or other health professional that your cholesterol is high?
4. **_CHOLCH3**: Cholesterol check within past five years

#### BMI
5. **_BMI5**: Body Mass Index (BMI)

#### Smoking
6. **SMOKE100**: Have you smoked at least 100 cigarettes in your entire life?   [Note:  5 packs = 100 cigarettes]

#### Other Chronic Health Conditions
7. **CVDSTRK3**: (Ever told) (you had) a stroke.
8. **_MICHD**: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)

#### Physical Activity
9.  **_TOTINDA**: Adults who reported doing physical activity or exercise during the past 30 days other than their regular job

#### Diet


#### Alcohol Consumption
10. **_RFDRHV8**: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week)

#### Health Care
11. **_HLTHPL1**: Adults who had some form of health insurance
12. **MEDCOST1**: Was there a time in the past 12 months when you needed to see a doctor but could not because you could not afford it?

#### Health General and Mental Health
13. **GENHLTH**: Would you say that in general your health is excellent, very good, good, fair, or poor?
14. **MENTHLTH**: Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?
15. **PHYSHLTH**: Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?
16. **DIFFWALK**: Do you have serious difficulty walking or climbing stairs?

#### Demographic Variables
17. **SEXVAR**: Sex of Respondent
18. **_AGEG5YR**: Fourteen-level age category
19. **EDUCA**: What is the highest grade or year of school you completed?
20. **INCOME3**: Is your annual household income from all sources: (If respondent refuses at any income level, code "Refused.")

In [5]:
brfss_df_selected = df[['DIABETE4',
                                         '_RFHYPE6',  
                                         'TOLDHI3', '_CHOLCH3', 
                                         '_BMI5', 
                                         'SMOKE100', 
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_RFDRHV8', 
                                         '_HLTHPL1', 'MEDCOST1', 
                                         'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', 
                                         'SEXVAR', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [6]:
brfss_df_selected.shape

(433323, 20)

In [7]:
brfss_df_selected.head()

,DIABETE4,_RFHYPE6,TOLDHI3,_CHOLCH3,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV8,_HLTHPL1,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
0,1.0,2.0,2.0,1.0,3047.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,88.0,88.0,1.0,2.0,13.0,5.0,99.0
1,3.0,2.0,1.0,1.0,2856.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,88.0,88.0,2.0,2.0,13.0,5.0,99.0
2,3.0,2.0,1.0,1.0,2231.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,4.0,2.0,6.0,1.0,2.0,13.0,4.0,2.0
3,3.0,1.0,2.0,1.0,2744.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,88.0,2.0,1.0,2.0,12.0,5.0,99.0
4,1.0,2.0,2.0,1.0,2585.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,4.0,88.0,88.0,1.0,2.0,12.0,5.0,7.0

In [8]:
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(338867, 20)

## Clean

In [9]:
# DIABETE4 = Diabetes Awareness
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({2:0, 3:0, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 9]
brfss_df_selected.DIABETE4.unique()

array([1., 0.])

In [10]:
#1 _RFHYPE6 = High Blood Pressure Awareness
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
brfss_df_selected._RFHYPE6.unique()

array([1., 0.])

In [11]:
# TOLDHI3 = Cholesterol Awareness
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
brfss_df_selected.TOLDHI3.unique()

array([0., 1.])

In [12]:
# _CHOLCH3 = Cholesterol check within past five years
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9 (don't know/refused)
brfss_df_selected['_CHOLCH3'] = brfss_df_selected['_CHOLCH3'].replace({3:0,2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._CHOLCH3 != 9]
brfss_df_selected._CHOLCH3.unique()

array([1., 0.])

In [13]:
# _BMI5 = Body mass index
# BMI are * 100
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([ 30.,  29.,  22.,  27.,  26.,  24.,  33.,  23.,  42.,  28.,  36.,
        25.,  38.,  44.,  37.,  31.,  32.,  52.,  34.,  54.,  48.,  20.,
        35.,  40.,  19.,  18.,  21.,  46.,  41.,  47.,  39.,  17.,  49.,
        43.,  45.,  51.,  50.,  16.,  15.,  56.,  13.,  62.,  77.,  68.,
        53.,  59.,  55.,  57.,  67.,  70.,  14.,  63.,  64.,  58.,  66.,
        60.,  65.,  72.,  82.,  61.,  76.,  12.,  86.,  83.,  75.,  71.,
        73.,  74.,  69.,  84.,  81.,  87., 100.,  78.,  95.,  89.,  80.,
        92.,  79.,  97.,  91.,  88.,  90.,  98.,  99.,  94.,  85.])

In [14]:
# SMOKE100 = Smoked at Least 100 Cigarettes
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([0., 1.])

In [15]:
# CVDSTRK3 = Chronic Health Conditions
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [16]:
# _MICHD = Ever had CHD or MI
# Coronary Heart Disease (CHD) and Myocardial Infarction (MI)
# Change 2 to 0 because this means they did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [17]:
# _TOTINDA = Leisure Time Physical Activity
# Change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([0., 1.])

In [18]:
# # _FRTLT1A = Consume Fruit 1 or more per day
# # Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_FRTLT1A'] = brfss_df_selected['_FRTLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1A != 9]
# brfss_df_selected._FRTLT1A.unique()

In [19]:
# # _VEGLT1A = Consume Vegetables 1 or more per day
# # Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_VEGLT1A'] = brfss_df_selected['_VEGLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1A != 9]
# brfss_df_selected._VEGLT1A.unique()

In [20]:
# _RFDRHV8 = Heavy Alcohol Consumption
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# Remove all 9 (don't know/refused)
brfss_df_selected['_RFDRHV8'] = brfss_df_selected['_RFDRHV8'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV8 != 9]
brfss_df_selected._RFDRHV8.unique()

array([0., 1.])

In [21]:
# _HLTHPLN = Have any health insurance
# Change 2 to 0 for no health insurance
# Remove all 9 (don't know/refused)
brfss_df_selected['_HLTHPL1'] = brfss_df_selected['_HLTHPL1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 9]
brfss_df_selected._HLTHPL1.unique()

array([1., 0.])

In [22]:
# MEDCOST1 = Could Not Afford To See Doctor
# Change 2 to 0 for no
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['MEDCOST1'] = brfss_df_selected['MEDCOST1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 9]
brfss_df_selected.MEDCOST1.unique()

array([0., 1.])

In [23]:
# GENHLTH = General Health
# 1 is Excellent -> 5 is Poor
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([2., 4., 3., 1., 5.])

In [24]:
# MENTHLTH = Number of Days Mental Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad mental health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([ 0.,  2.,  3., 25., 10., 30., 20., 15.,  5., 12.,  4.,  1.,  6.,
       21.,  7., 14., 29.,  8., 16., 17.,  9., 28., 11., 18., 22., 24.,
       13., 27., 26., 19., 23.])

In [25]:
# PHYSHLTH = Number of Days Physical Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad physical health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([ 0.,  6.,  2.,  1.,  5.,  4., 15., 30., 21., 10., 25.,  7., 20.,
        3., 12., 26., 14.,  8., 24., 18., 13., 28., 16., 17., 11., 22.,
       27.,  9., 29., 23., 19.])

In [26]:
# DIFFWALK = Difficulty Walking or Climbing Stairs
# Change 2 to 0 for no.
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([1., 0.])

In [27]:
# SEXVAR = Respondent Sex
# Men are at higher risk for heart disease
# Change 2 to 0 (female as 0)
brfss_df_selected['SEXVAR'] = brfss_df_selected['SEXVAR'].replace({2:0})
brfss_df_selected.SEXVAR.unique()

array([0., 1.])

In [28]:
# _AGEG5YR = Reported age in five-year age categories
# 5 year increments. It is already ordinal. 1 is 18-24 all the way up to 13 which is 80 and older
# Remove all 14 (don't know or missing)
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([13., 12.,  9.,  8., 10., 11.,  6.,  4.,  5.,  7.,  2.,  1.,  3.])

In [29]:
# EDUCA = Education Level
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([5., 4., 6., 3., 2., 1.])

In [30]:
# INCOME3 = Income Level
# This is already an ordinal variable with 1 being less than $10,000 all the way up to 11 being $200,000 or more
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected.INCOME3.unique()

array([ 2.,  7.,  6.,  9.,  3.,  5.,  4.,  8., 11., 10.,  1.])

In [31]:
brfss_df_selected.shape

(261589, 20)

In [32]:
brfss_df_selected.head()

,DIABETE4,_RFHYPE6,TOLDHI3,_CHOLCH3,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV8,_HLTHPL1,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
2,0.0,1.0,1.0,1.0,22.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,4.0,2.0,6.0,1.0,0.0,13.0,4.0,2.0
4,1.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0,0.0,0.0,1.0,0.0,12.0,5.0,7.0
5,0.0,1.0,1.0,1.0,30.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,3.0,2.0,0.0,0.0,9.0,5.0,7.0
8,0.0,1.0,1.0,1.0,33.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,5.0,1.0,0.0,13.0,5.0,6.0
9,1.0,1.0,1.0,1.0,23.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,4.0,7.0

In [33]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    216762
1.0     44827
dtype: int64

In [34]:
#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes', '_RFHYPE6':'HighBP', 'TOLDHI3':'HighChol', '_CHOLCH3':'CholCheck', '_BMI5':'BMI', 'SMOKE100':'Smoker', 'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', '_TOTINDA':'PhysActivity', '_FRTLT1A':'Fruits', '_VEGLT1A':"Veggies", '_RFDRHV8':'HvyAlcoholConsump', '_HLTHPL1':'AnyHealthcare', 'MEDCOST1':'NoDocbcCost', 'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 'SEXVAR':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME3':'Income' })

In [35]:
brfss.head()

,Diabetes,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
2,0.0,1.0,1.0,1.0,22.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,4.0,2.0,6.0,1.0,0.0,13.0,4.0,2.0
4,1.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0,0.0,0.0,1.0,0.0,12.0,5.0,7.0
5,0.0,1.0,1.0,1.0,30.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,3.0,2.0,0.0,0.0,9.0,5.0,7.0
8,0.0,1.0,1.0,1.0,33.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,5.0,1.0,0.0,13.0,5.0,6.0
9,1.0,1.0,1.0,1.0,23.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,4.0,7.0

In [36]:
brfss.shape

(261589, 20)

In [37]:
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    216762
1.0     44827
dtype: int64

In [38]:
brfss.to_csv('diabetes_BRFSS2023.csv', sep=",", index=False)