In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('LLCP2024.csv')

In [3]:
df.shape

(457670, 301)

In [4]:
pd.set_option('display.max_columns', 500)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,NUMADULT,RESPSLC1,LANDSEX3,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX3,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINS2,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,RENTHOM1,NUMHHOL4,NUMPHON4,CPDEMO1C,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW3,LCSFIRST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,ALCDAY4,AVEDRNK4,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,IMFVPLA5,PNEUVAC4,HIVTST7,HIVTSTD3,HIVRISK5,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,ARTHEXER,SHINGLE2,HPVADVC4,HPVADSH1,TETANUS1,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,PSATEST1,PSATIME1,PCPSARS2,PSASUGS1,PCSTALK2,CIMEMLO1,CDWORRY,CDDISCU1,CDHOUS1,CDSOCIA1,CAREGIV1,CRGVREL5,CRGVPRB4,CRGVALZD,CRGVNURS,CRGVPER2,CRGVHOU2,CRGVHRS2,CRGVLNG2,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,LSATISFY,EMTSUPRT,SDLONELY,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,HOWSAFE1,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,SSBSUGR2,SSBFRUT3,FIREARM5,GUNLOAD,LOADULK2,RCSGEND1,RCSXBRTH,RCSRLTN2,CASTHDX2,CASTHNO2,SOMALE,SOFEMALE,HADSEX,PFPPRVN4,TYPCNTR9,NOBCUSE8,QSTVER,QSTLANG,HPVDSHT,ICFQSTVR,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPL2,_HCVU654,_TOTINDA,_EXTETH3,_ALTETH3,_DENVST3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_RFMAM23,_MAM402Y,_CRVSCRN,_RFPAP37,_HPV5YR1,_PAPHPV1,_HADCOLN,_CLNSCP2,_HADSIGM,_SGMSCP2,_SGMS102,_RFBLDS6,_STOLDN2,_VIRCOL2,_SBONTI2,_CRCREC3,_SMOKER3,_RFSMOK3,_CURECI3,LCSLAST_,LCSNUMC_,_LCSAGE,_LCSYSMK,_PACKDAY,_PACKYRS,_LCSYQTS,_LCSSMKG,_LCSELIG,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000001',2.024000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,88.0,88.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,3.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,131.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3.0,NaN,NaN,1.0,1.0,7.0,1.0,7.0,2.0,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,1.0,7.0,NaN,888.0,NaN,NaN,NaN,1.0,777777.0,1.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,10.0,1.0,NaN,NaN,1.0,1.0,1.0,11011.0,28.393219,1.0,28.393219,1.0,NaN,NaN,NaN,NaN,1.0,0.465294,220.149005,261.525511,1.0,2.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,12.0,2.0,78.0,6.0,64.0,163.0,5942.0,2249.0,2.0,1.0,1.0,2.0,9.0,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,6.0,2.0,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000002',2.024000e+09,1.0,1.0,NaN,1.0,2.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,88.0,88.0,NaN,3.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,1.0,6.0,1.0,2.0,NaN,1.0,1.0,7.0,88.0,11.0,NaN,180.0,510.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,4.0,NaN,NaN,1.0,2.0,NaN,1.0,1.0,2.0,NaN,NaN,1.0,3.0,3.0,1.0,25.0,20.0,2.0,NaN,NaN,888.0,NaN,NaN,NaN,1.0,92023.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0,NaN,NaN,1.0,1.0,1.0,11011.0,28.393219,2.0,56.786438,1.0,NaN,NaN,NaN,NaN,1.0,0.465294,440.298009,307.169688,1.0,1.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,13.0,2.0,80.0,6.0,70.0,178.0,8165.0,2583.0,3.0,2.0,1.0,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0,27.0,20.0,2.0,2.0,100.0,2.0,53.0,5.0,2.0,4.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
2,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000003',2.024000e+09,1.0,1.0,NaN,1.0,2.0,1.0,3.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,30.0,88.0,1.0,1.0,3.0,1.0,4.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,6.0,5.0,1.0,2.0,NaN,8.0,1.0,1.0,88.0,99.0,NaN,195.0,606.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3.0,1.0,14.0,15.0,2.0,NaN,NaN,230.0,2.0,3.0,5.0,2.0,NaN,NaN,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0,NaN,NaN,2.0,1.0,5.0,11011.0,28.393219,3.0,85.179657,1.0,NaN,NaN,NaN,NaN,9.0,NaN,1938.892385,2939.862806,1.0,3.0,1.0,1.0,1.0,1.0,2.0,NaN,2.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,8.0,1.0,59.0,5.0,78.0,198.0,8845.0,2253.0,2.0,1.0,1.0,3.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,1.0,NaN,15.0,2.0,45.0,75.0,34.0,NaN,1.0,1.0,4.0,2.0,1.0,1.000000e+02,2.0,1.400000e+03,1.0,NaN,NaN,2.0
3,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000004',2.024000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,88.0,88.0,NaN,3.0,1.0,2.0,1.0,1.0,1.0,8.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,1.0,6.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,6.0,NaN,165.0,508.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,3.0,7.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,1.0,7.0,NaN,888.0,NaN,NaN,NaN,1.0,102023.0,5.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0,NaN,NaN,2.0,1.0,5.0,11011.0,28.393219,1.0,28.393219,1.0,NaN,NaN,NaN,NaN,1.0,0.465294,220.149005,153.584844,1.0,1.0,1.0,1.0,9.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,13.0,2.0,80.0,6.0,68.0,173.0,7484.0,2509.0,3.0,2.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,6.0,2.0,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
4,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000005',2.024000e+09,1.0,1.0,NaN,1.0,2.0,1.0,3.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,88.0,88.0,NaN,5.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,5.0,5.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,3.0,NaN,130.0,508.0,1.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,4.0,NaN,NaN,1.0,2.0,NaN,888.0,NaN,NaN,NaN,1.0,92023.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,1.0,2.0,2.0,5.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0,NaN,NaN,1.0,1.0,1.0,11011.0,28.393219,3.0,85.179657,1.0,NaN,NaN,NaN,NaN,1.0,0.465294,660.447014,1229.623036,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,2.0,1.0,1.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0,47.0,4.0,68.0,173.0,5897.0,1977.0,2.0,1.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,6.0,2.0,3.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0

## Selected Attributes

### Response Variables:
1. **DIABETE4**:   (Ever told) (you had) diabetes?  (If Yes -  and respondent is female, ask Was this only when you were pregnant? If Respondent says pre-diabetes or borderline diabetes, use response code 4.)

### Predictor Variables:

#### High Blood Pressure

#### High Cholesterol

#### BMI
5. **_BMI5**: Body Mass Index (BMI)

#### Smoking
6. **SMOKE100**: Have you smoked at least 100 cigarettes in your entire life?   [Note:  5 packs = 100 cigarettes]

#### Other Chronic Health Conditions
7. **CVDSTRK3**: (Ever told) (you had) a stroke.
8. **_MICHD**: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)

#### Physical Activity
9.  **_TOTINDA**: Adults who reported doing physical activity or exercise during the past 30 days other than their regular job

#### Diet


#### Alcohol Consumption
10. **_RFDRHV8**: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week)

#### Health Care
11. **_HLTHPLN**: Adults who had some form of health insurance
12. **MEDCOST1**: Was there a time in the past 12 months when you needed to see a doctor but could not because you could not afford it?

#### Health General and Mental Health
13. **GENHLTH**: Would you say that in general your health is excellent, very good, good, fair, or poor?
14. **MENTHLTH**: Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?
15. **PHYSHLTH**: Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?
16. **DIFFWALK**: Do you have serious difficulty walking or climbing stairs?

#### Demographic Variables
17. **SEXVAR**: Sex of Respondent
18. **_AGEG5YR**: Fourteen-level age category
19. **EDUCA**: What is the highest grade or year of school you completed?
20. **INCOME3**: Is your annual household income from all sources: (If respondent refuses at any income level, code "Refused.")

In [5]:
brfss_df_selected = df[['DIABETE4',
                                         '_BMI5', 
                                         'SMOKE100', 
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_RFDRHV9', 
                                         '_HLTHPL2', 'MEDCOST1', 
                                         'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', 
                                         'SEXVAR', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [6]:
brfss_df_selected.shape

(457670, 17)

In [7]:
brfss_df_selected.head()

,DIABETE4,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV9,_HLTHPL2,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
0,3.0,2249.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,88.0,2.0,2.0,2.0,12.0,4.0,99.0
1,3.0,2583.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,88.0,88.0,2.0,1.0,13.0,6.0,11.0
2,3.0,2253.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,88.0,30.0,2.0,1.0,8.0,5.0,99.0
3,3.0,2509.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,88.0,88.0,2.0,1.0,13.0,6.0,6.0
4,3.0,1977.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,88.0,88.0,1.0,1.0,6.0,5.0,3.0

In [8]:
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(397810, 17)

## Clean

In [9]:
# DIABETE4 = Diabetes Awareness
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({2:0, 3:0, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 9]
brfss_df_selected.DIABETE4.unique()

array([0., 1.])

In [10]:
# #1 _RFHYPE6 = High Blood Pressure Awareness
# #Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
# brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
# brfss_df_selected._RFHYPE6.unique()

In [11]:
# # TOLDHI3 = Cholesterol Awareness
# # Change 2 to 0 because it is No
# # Remove all 7 (dont knows)
# # Remove all 9 (refused)
# brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
# brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
# brfss_df_selected.TOLDHI3.unique()

In [12]:
# # _CHOLCH3 = Cholesterol check within past five years
# # Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# # Remove 9 (don't know/refused)
# brfss_df_selected['_CHOLCH3'] = brfss_df_selected['_CHOLCH3'].replace({3:0,2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._CHOLCH3 != 9]
# brfss_df_selected._CHOLCH3.unique()

In [13]:
# _BMI5 = Body mass index
# BMI are * 100
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([ 22.,  26.,  23.,  25.,  20.,  33.,  31.,  36.,  41.,  21.,  24.,
        27.,  30.,  29.,  28.,  32.,  34.,  18.,  35.,  43.,  39.,  40.,
        42.,  19.,  45.,  46.,  14.,  37.,  38.,  48.,  59.,  44.,  16.,
        63.,  52.,  58.,  17.,  47.,  51.,  53.,  61.,  15.,  13.,  50.,
        62.,  49.,  71.,  69.,  83.,  82.,  72.,  56.,  54.,  65.,  55.,
        67.,  81.,  12.,  64.,  66.,  57.,  75.,  68.,  74.,  93.,  89.,
        88.,  60.,  73.,  80.,  77.,  70.,  85.,  91.,  90.,  76.,  84.,
        95.,  97.,  92.,  79.,  96.,  87.,  94.,  78.,  98., 100.,  86.])

In [14]:
# SMOKE100 = Smoked at Least 100 Cigarettes
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([0., 1.])

In [15]:
# CVDSTRK3 = Chronic Health Conditions
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [16]:
# _MICHD = Ever had CHD or MI
# Coronary Heart Disease (CHD) and Myocardial Infarction (MI)
# Change 2 to 0 because this means they did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [17]:
# _TOTINDA = Leisure Time Physical Activity
# Change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([1., 0.])

In [18]:
# # _FRTLT1A = Consume Fruit 1 or more per day
# # Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_FRTLT1A'] = brfss_df_selected['_FRTLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1A != 9]
# brfss_df_selected._FRTLT1A.unique()

In [19]:
# # _VEGLT1A = Consume Vegetables 1 or more per day
# # Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_VEGLT1A'] = brfss_df_selected['_VEGLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1A != 9]
# brfss_df_selected._VEGLT1A.unique()

In [20]:
# _RFDRHV8 = Heavy Alcohol Consumption
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# Remove all 9 (don't know/refused)
brfss_df_selected['_RFDRHV9'] = brfss_df_selected['_RFDRHV9'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV9 != 9]
brfss_df_selected._RFDRHV9.unique()

array([0., 1.])

In [21]:
# _HLTHPLN = Have any health insurance
# Change 2 to 0 for no health insurance
# Remove all 9 (don't know/refused)
brfss_df_selected['_HLTHPL2'] = brfss_df_selected['_HLTHPL2'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL2 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL2 != 9]
brfss_df_selected._HLTHPL2.unique()

array([1., 0.])

In [22]:
# MEDCOST1 = Could Not Afford To See Doctor
# Change 2 to 0 for no
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['MEDCOST1'] = brfss_df_selected['MEDCOST1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 9]
brfss_df_selected.MEDCOST1.unique()

array([0., 1.])

In [23]:
# GENHLTH = General Health
# 1 is Excellent -> 5 is Poor
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([3., 1., 2., 4., 5.])

In [24]:
# MENTHLTH = Number of Days Mental Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad mental health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([ 0., 15.,  1.,  2.,  8., 10.,  7.,  6., 30.,  5.,  4., 25.,  3.,
       20., 29., 11., 12., 14., 26., 17., 23., 28., 21., 18.,  9., 22.,
       13., 19., 16., 27., 24.])

In [25]:
# PHYSHLTH = Number of Days Physical Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad physical health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([ 2.,  0., 30.,  7.,  5., 14.,  1., 25.,  6.,  3.,  4., 15., 10.,
       20., 12.,  8., 29., 21.,  9., 28., 19., 16., 18., 27., 17., 24.,
       11., 22., 13., 26., 23.])

In [26]:
# DIFFWALK = Difficulty Walking or Climbing Stairs
# Change 2 to 0 for no.
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([0., 1.])

In [27]:
# SEXVAR = Respondent Sex
# Men are at higher risk for heart disease
# Change 2 to 0 (female as 0)
brfss_df_selected['SEXVAR'] = brfss_df_selected['SEXVAR'].replace({2:0})
brfss_df_selected.SEXVAR.unique()

array([0., 1.])

In [28]:
# _AGEG5YR = Reported age in five-year age categories
# 5 year increments. It is already ordinal. 1 is 18-24 all the way up to 13 which is 80 and older
# Remove all 14 (don't know or missing)
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([12., 13.,  8.,  6.,  7., 11., 10.,  9.,  5.,  4.,  2.,  1.,  3.])

In [29]:
# EDUCA = Education Level
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([4., 6., 5., 3., 2., 1.])

In [30]:
# INCOME3 = Income Level
# This is already an ordinal variable with 1 being less than $10,000 all the way up to 11 being $200,000 or more
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected.INCOME3.unique()

array([11.,  6.,  3.,  9.,  5.,  7.,  8.,  2., 10.,  4.,  1.])

In [31]:
brfss_df_selected.shape

(305632, 17)

In [32]:
brfss_df_selected.head()

,DIABETE4,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV9,_HLTHPL2,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
1,0.0,26.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,13.0,6.0,11.0
3,0.0,25.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,13.0,6.0,6.0
4,0.0,20.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,6.0,5.0,3.0
5,1.0,33.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,0.0,7.0,0.0,1.0,7.0,4.0,9.0
6,0.0,31.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,11.0,5.0,6.0

In [33]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    254692
1.0     50940
dtype: int64

In [34]:
#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes', '_RFHYPE6':'HighBP', 'TOLDHI3':'HighChol', '_CHOLCH3':'CholCheck', '_BMI5':'BMI', 'SMOKE100':'Smoker', 'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', '_TOTINDA':'PhysActivity', '_FRTLT1A':'Fruits', '_VEGLT1A':"Veggies", '_RFDRHV9':'HvyAlcoholConsump', '_HLTHPL2':'AnyHealthcare', 'MEDCOST1':'NoDocbcCost', 'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 'SEXVAR':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME3':'Income' })

In [35]:
brfss.head()

,Diabetes,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
1,0.0,26.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,13.0,6.0,11.0
3,0.0,25.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,13.0,6.0,6.0
4,0.0,20.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,6.0,5.0,3.0
5,1.0,33.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,0.0,7.0,0.0,1.0,7.0,4.0,9.0
6,0.0,31.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,11.0,5.0,6.0

In [36]:
brfss.shape

(305632, 17)

In [37]:
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    254692
1.0     50940
dtype: int64

In [38]:
brfss.to_csv('diabetes_BRFSS2024.csv', sep=",", index=False)