In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('LLCP2021.csv')

In [3]:
df.shape

(438693, 303)

In [4]:
pd.set_option('display.max_columns', 500)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,COLGSEX,NUMADULT,LANDSEX,NUMMEN,NUMWOMEN,RESPSLCT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINSR,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPHIGH6,BPMEDS,CHOLCHK3,TOLDHI3,CHOLMED3,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD3,ADDEPEV3,CHCKDNY2,DIABETE4,DIABAGE3,HAVARTH5,ARTHEXER,ARTHEDU,LMTJOIN3,ARTHDIS2,JOINPAI2,MARITAL,EDUCA,RENTHOM1,NUMHHOL3,NUMPHON3,CPDEMO1B,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW1,ALCDAY5,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,IMFVPLA2,PNEUVAC4,HIVTST7,HIVTSTD3,FRUIT2,FRUITJU2,FVGREEN1,FRENCHF1,POTATOE1,VEGETAB2,PDIABTST,PREDIAB1,INSULIN1,BLDSUGAR,FEETCHK3,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM1,DIABEYE,DIABEDU,TOLDCFS,HAVECFS,WORKCFS,TOLDHEPC,TRETHEPC,PRIRHEPC,HAVEHEPC,HAVEHEPB,MEDSHEPB,HPVADVC4,HPVADSHT,TETANUS1,SHINGLE2,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSCN,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,PSATEST1,PSATIME1,PCPSARS2,PCSTALK,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES1,SMALSTOL,STOLTEST,STOOLDN1,BLDSTFIT,SDNATES1,CNCRDIFF,CNCRAGE,CNCRTYP1,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,HOMBPCHK,HOMRGCHK,WHEREBP,SHAREBP,WTCHSALT,DRADVISE,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,MARIJAN1,USEMRJN3,RSNMRJN2,LASTSMK2,STOPSMK2,FIREARM5,GUNLOAD,LOADULK2,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,_CPRACE1,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_RFHYPE6,_CHOLCH3,_RFCHOL3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR3,_LMTACT3,_LMTWRK3,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI1,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWK1,_RFDRHV7,_FLSHOT7,_PNEUMO3,_AIDTST4,FTJUDA2_,FRUTDA2_,GRENDA1_,FRNCHDA_,POTADA1_,VEGEDA2_,_MISFRT1,_MISVEG1,_FRTRES1,_VEGRES1,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1
0,1.0,1.0,b'01192021',b'01',b'19',b'2021',1100.0,b'2021000001',2.021000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,5.0,20.0,10.0,88.0,3.0,1.0,2.0,2.0,2.0,3.0,NaN,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,2.0,2.0,2.0,1.0,8.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,5.0,NaN,72.0,411.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,888.0,NaN,NaN,NaN,1.0,92020.0,1.0,1.0,2.0,NaN,101.0,555.0,204.0,203.0,201.0,101.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,39.766158,2.0,79.532315,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.519019,874.242902,744.745531,2.0,3.0,2.0,1.0,9.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,11.0,2.0,70.0,6.0,59.0,150.0,3266.0,1454.0,1.0,1.0,1.0,2.0,3.0,3.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,5.397605e-79,100.0,5.700000e+01,4.300000e+01,14.0,100.0,5.397605e-79,5.397605e-79,1.0,1.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
1,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000002',2.021000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,1.0,98.0,1.0,1.0,2.0,1.0,1.0,10.0,9.0,6.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,77.0,NaN,7777.0,506.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,101.0,555.0,201.0,555.0,201.0,207.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,2.0,11011.0,39.766158,2.0,79.532315,2.0,9.0,NaN,NaN,NaN,NaN,1.0,0.519019,874.242902,299.137394,1.0,1.0,1.0,1.0,9.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,67.0,6.0,66.0,168.0,NaN,NaN,NaN,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,5.397605e-79,100.0,1.400000e+01,5.397605e-79,14.0,100.0,5.397605e-79,5.397605e-79,1.0,1.0,100.0,128.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
2,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000003',2.021000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,98.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,3.0,NaN,170.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,101.0,555.0,555.0,201.0,201.0,203.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,39.766158,2.0,79.532315,2.0,9.0,NaN,NaN,NaN,NaN,1.0,0.519019,874.242902,587.862986,1.0,1.0,1.0,1.0,9.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,11.0,2.0,72.0,6.0,65.0,165.0,7711.0,2829.0,3.0,2.0,1.0,2.0,2.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,5.397605e-79,100.0,5.397605e-79,1.400000e+01,14.0,43.0,5.397605e-79,5.397605e-79,1.0,1.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79
3,1.0,1.0,b'01172021',b'01',b'17',b'2021',1100.0,b'2021000004',2.021000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,10.0,88.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,56.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,195.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,101.0,3.0,1.0,6.0,1.0,102020.0,1.0,2.0,2.0,NaN,203.0,205.0,303.0,204.0,308.0,205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,3.0,11011.0,39.766158,2.0,79.532315,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.519019,874.242902,1099.621573,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,9.0,1.0,62.0,5.0,64.0,163.0,8845.0,3347.0,4.0,2.0,1.0,2.0,5.0,4.0,1.0,1.0,1.0,1.400000e+01,2.0,3.000000e+02,1.0,NaN,NaN,2.0,7.100000e+01,43.0,1.000000e+01,5.700000e+01,27.0,71.0,5.397605e-79,5.397605e-79,1.0,1.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
4,1.0,1.0,b'01152021',b'01',b'15',b'2021',1100.0,b'2021000005',2.021000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,30.0,88.0,30.0,3.0,1.0,2.0,1.0,1.0,4.0,NaN,2.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,65.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,3.0,1.0,2.0,NaN,8.0,2.0,8.0,88.0,4.0,NaN,206.0,511.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,1.0,92020.0,1.0,1.0,1.0,777777.0,101.0,555.0,101.0,202.0,202.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,2.0,1.0,2.0,11011.0,39.766158,2.0,79.532315,6.0,9.0,NaN,NaN,NaN,NaN,9.0,NaN,2144.768999,1711.825866,2.0,3.0,1.0,1.0,9.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,2.0,3.0,3.0,1.0,7.0,2.0,7.0,2.0,4.0,7.0,1.0,12.0,2.0,76.0,6.0,71.0,180.0,9344.0,2873.0,3.0,2.0,1.0,1.0,2.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,5.397605e-79,100.0,1.000000e+02,2.900000e+01,29.0,100.0,5.397605e-79,5.397605e-79,1.0,1.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79

## Selected Attributes

### Response Variables:
1. **DIABETE4**:   (Ever told) (you had) diabetes?  (If Yes -  and respondent is female, ask Was this only when you were pregnant? If Respondent says pre-diabetes or borderline diabetes, use response code 4.)

### Predictor Variables:

#### High Blood Pressure
2. **_RFHYPE6**:  Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional

#### High Cholesterol
3. **TOLDHI3**: Have you ever been told by a doctor, nurse or other health professional that your cholesterol is high?
4. **_CHOLCH3**: Cholesterol check within past five years

#### BMI
5. **_BMI5**: Body Mass Index (BMI)

#### Smoking
6. **SMOKE100**: Have you smoked at least 100 cigarettes in your entire life?   [Note:  5 packs = 100 cigarettes]

#### Other Chronic Health Conditions
7. **CVDSTRK3**: (Ever told) (you had) a stroke.
8. **_MICHD**: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)

#### Physical Activity
9.  **_TOTINDA**: Adults who reported doing physical activity or exercise during the past 30 days other than their regular job

#### Diet


#### Alcohol Consumption
10. **_RFDRHV8**: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week)

#### Health Care
11. **_HLTHPL1**: Adults who had some form of health insurance
12. **MEDCOST1**: Was there a time in the past 12 months when you needed to see a doctor but could not because you could not afford it?

#### Health General and Mental Health
13. **GENHLTH**: Would you say that in general your health is excellent, very good, good, fair, or poor?
14. **MENTHLTH**: Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?
15. **PHYSHLTH**: Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?
16. **DIFFWALK**: Do you have serious difficulty walking or climbing stairs?

#### Demographic Variables
17. **SEXVAR**: Sex of Respondent
18. **_AGEG5YR**: Fourteen-level age category
19. **EDUCA**: What is the highest grade or year of school you completed?
20. **INCOME3**: Is your annual household income from all sources: (If respondent refuses at any income level, code "Refused.")

In [5]:
brfss_df_selected = df[['DIABETE4',
                                         '_RFHYPE6',  
                                         'TOLDHI3', '_CHOLCH3', 
                                         '_BMI5', 
                                         'SMOKE100', 
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_RFDRHV7', 
                                         '_HLTHPLN', 'MEDCOST1', 
                                         'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', 
                                         'SEXVAR', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [6]:
brfss_df_selected.shape

(438693, 20)

In [7]:
brfss_df_selected.head()

,DIABETE4,_RFHYPE6,TOLDHI3,_CHOLCH3,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV7,_HLTHPLN,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
0,3.0,1.0,1.0,1.0,1454.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,5.0,10.0,20.0,2.0,2.0,11.0,4.0,5.0
1,1.0,2.0,1.0,1.0,NaN,2.0,2.0,1.0,1.0,1.0,1.0,2.0,3.0,88.0,88.0,1.0,2.0,10.0,6.0,77.0
2,1.0,2.0,2.0,1.0,2829.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,88.0,88.0,2.0,2.0,11.0,4.0,3.0
3,1.0,2.0,1.0,1.0,3347.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,10.0,88.0,2.0,2.0,9.0,4.0,7.0
4,1.0,1.0,1.0,1.0,2873.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,5.0,88.0,30.0,1.0,1.0,12.0,3.0,4.0

In [8]:
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(330355, 20)

## Clean

In [9]:
# DIABETE4 = Diabetes Awareness
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({2:0, 3:0, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 9]
brfss_df_selected.DIABETE4.unique()

array([0., 1.])

In [10]:
#1 _RFHYPE6 = High Blood Pressure Awareness
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
brfss_df_selected._RFHYPE6.unique()

array([0., 1.])

In [11]:
# TOLDHI3 = Cholesterol Awareness
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
brfss_df_selected.TOLDHI3.unique()

array([1., 0.])

In [12]:
# _CHOLCH3 = Cholesterol check within past five years
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9 (don't know/refused)
brfss_df_selected['_CHOLCH3'] = brfss_df_selected['_CHOLCH3'].replace({3:0,2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._CHOLCH3 != 9]
brfss_df_selected._CHOLCH3.unique()

array([1., 0.])

In [13]:
# _BMI5 = Body mass index
# BMI are * 100
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([15., 28., 33., 29., 24., 46., 23., 40., 27., 35., 18., 30., 25.,
       36., 22., 31., 45., 26., 14., 38., 21., 32., 20., 19., 34., 41.,
       43., 44., 39., 37., 16., 42., 50., 51., 17., 52., 47., 49., 56.,
       57., 48., 58., 61., 53., 63., 64., 54., 68., 55., 62., 13., 59.,
       89., 66., 77., 60., 87., 69., 72., 75., 67., 71., 65., 82., 86.,
       70., 78., 12., 74., 98., 73., 84., 76., 80., 83., 79., 99., 88.,
       81., 90., 92., 91., 95., 85., 94.])

In [14]:
# SMOKE100 = Smoked at Least 100 Cigarettes
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([1., 0.])

In [15]:
# CVDSTRK3 = Chronic Health Conditions
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [16]:
# _MICHD = Ever had CHD or MI
# Coronary Heart Disease (CHD) and Myocardial Infarction (MI)
# Change 2 to 0 because this means they did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [17]:
# _TOTINDA = Leisure Time Physical Activity
# Change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([0., 1.])

In [18]:
# # _FRTLT1A = Consume Fruit 1 or more per day
# # Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_FRTLT1A'] = brfss_df_selected['_FRTLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1A != 9]
# brfss_df_selected._FRTLT1A.unique()

In [19]:
# # _VEGLT1A = Consume Vegetables 1 or more per day
# # Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_VEGLT1A'] = brfss_df_selected['_VEGLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1A != 9]
# brfss_df_selected._VEGLT1A.unique()

In [20]:
# _RFDRHV8 = Heavy Alcohol Consumption
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# Remove all 9 (don't know/refused)
brfss_df_selected['_RFDRHV7'] = brfss_df_selected['_RFDRHV7'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV7 != 9]
brfss_df_selected._RFDRHV7.unique()

array([0., 1.])

In [21]:
# _HLTHPLN = Have any health insurance
# Change 2 to 0 for no health insurance
# Remove all 9 (don't know/refused)
brfss_df_selected['_HLTHPLN'] = brfss_df_selected['_HLTHPLN'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 9]
brfss_df_selected._HLTHPLN.unique()

array([1., 0.])

In [22]:
# MEDCOST1 = Could Not Afford To See Doctor
# Change 2 to 0 for no
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['MEDCOST1'] = brfss_df_selected['MEDCOST1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 9]
brfss_df_selected.MEDCOST1.unique()

array([0., 1.])

In [23]:
# GENHLTH = General Health
# 1 is Excellent -> 5 is Poor
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([5., 2., 3., 4., 1.])

In [24]:
# MENTHLTH = Number of Days Mental Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad mental health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([10.,  0.,  5., 25.,  2.,  7., 30.,  3., 14., 20.,  8.,  1., 15.,
        4., 28., 24., 21., 12.,  6., 22., 27., 18., 13., 17., 16.,  9.,
       19., 29., 23., 11., 26.])

In [25]:
# PHYSHLTH = Number of Days Physical Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad physical health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([20.,  0., 30., 25.,  1.,  4., 10.,  2.,  3., 15.,  8., 13., 14.,
        5.,  7.,  6., 17., 22., 24., 29., 18.,  9., 16., 26., 12., 28.,
       21., 27., 11., 19., 23.])

In [26]:
# DIFFWALK = Difficulty Walking or Climbing Stairs
# Change 2 to 0 for no.
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([0., 1.])

In [27]:
# SEXVAR = Respondent Sex
# Men are at higher risk for heart disease
# Change 2 to 0 (female as 0)
brfss_df_selected['SEXVAR'] = brfss_df_selected['SEXVAR'].replace({2:0})
brfss_df_selected.SEXVAR.unique()

array([0., 1.])

In [28]:
# _AGEG5YR = Reported age in five-year age categories
# 5 year increments. It is already ordinal. 1 is 18-24 all the way up to 13 which is 80 and older
# Remove all 14 (don't know or missing)
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([11.,  9., 12., 13., 10.,  7.,  6.,  8.,  4.,  3.,  5.,  2.,  1.])

In [29]:
# EDUCA = Education Level
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([4., 3., 5., 6., 2., 1.])

In [30]:
# INCOME3 = Income Level
# This is already an ordinal variable with 1 being less than $10,000 all the way up to 11 being $200,000 or more
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected.INCOME3.unique()

array([ 5.,  3.,  7.,  4.,  6.,  8.,  2.,  9., 10.,  1., 11.])

In [31]:
brfss_df_selected.shape

(253302, 20)

In [32]:
brfss_df_selected.head()

,DIABETE4,_RFHYPE6,TOLDHI3,_CHOLCH3,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV7,_HLTHPLN,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
0,0.0,0.0,1.0,1.0,15.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,10.0,20.0,0.0,0.0,11.0,4.0,5.0
2,1.0,1.0,0.0,1.0,28.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,4.0,3.0
3,1.0,1.0,1.0,1.0,33.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,10.0,0.0,0.0,0.0,9.0,4.0,7.0
4,1.0,0.0,1.0,1.0,29.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,5.0,0.0,30.0,1.0,1.0,12.0,3.0,4.0
5,0.0,0.0,0.0,1.0,24.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,13.0,5.0,6.0

In [33]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    211076
1.0     42226
dtype: int64

In [34]:
#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes', '_RFHYPE6':'HighBP', 'TOLDHI3':'HighChol', '_CHOLCH3':'CholCheck', '_BMI5':'BMI', 'SMOKE100':'Smoker', 'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', '_TOTINDA':'PhysActivity', '_FRTLT1A':'Fruits', '_VEGLT1A':"Veggies", '_RFDRHV7':'HvyAlcoholConsump', '_HLTHPLN':'AnyHealthcare', 'MEDCOST1':'NoDocbcCost', 'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 'SEXVAR':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME3':'Income' })

In [35]:
brfss.head()

,Diabetes,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,0.0,1.0,1.0,15.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,10.0,20.0,0.0,0.0,11.0,4.0,5.0
2,1.0,1.0,0.0,1.0,28.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,4.0,3.0
3,1.0,1.0,1.0,1.0,33.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,10.0,0.0,0.0,0.0,9.0,4.0,7.0
4,1.0,0.0,1.0,1.0,29.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,5.0,0.0,30.0,1.0,1.0,12.0,3.0,4.0
5,0.0,0.0,0.0,1.0,24.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,13.0,5.0,6.0

In [36]:
brfss.shape

(253302, 20)

In [37]:
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    211076
1.0     42226
dtype: int64

In [38]:
brfss.to_csv('diabetes_BRFSS2021.csv', sep=",", index=False)