In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('LLCP2022.csv')

In [3]:
df.shape

(445132, 328)

In [4]:
pd.set_option('display.max_columns', 500)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,COLGSEX1,NUMADULT,LANDSEX1,NUMMEN,NUMWOMEN,RESPSLCT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX1,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINSR,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,RENTHOM1,NUMHHOL4,NUMPHON4,CPDEMO1C,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW2,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,ALCDAY4,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,PNEUVAC4,TETANUS1,HIVTST7,HIVTSTD3,HIVRISK5,COVIDPOS,COVIDSMP,COVIDPRM,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,TOLDCFS,HAVECFS,WORKCFS,IMFVPLA3,HPVADVC4,HPVADSHT,SHINGLE2,COVIDVA1,COVACGET,COVIDNU1,COVIDINT,COVIDFS1,COVIDSE1,COPDCOGH,COPDFLEM,COPDBRTH,COPDBTST,COPDSMOK,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,PSATEST1,PSATIME1,PCPSARS2,PSASUGST,PCSTALK1,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,LSATISFY,EMTSUPRT,SDHISOLT,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,SDHSTRE1,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,ASBIALCH,ASBIDRNK,ASBIBING,ASBIADVC,ASBIRDUC,FIREARM5,GUNLOAD,LOADULK2,RCSGEND1,RCSXBRTH,RCSRLTN2,CASTHDX2,CASTHNO2,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,HADSEX,PFPPRVN4,TYPCNTR9,BRTHCNT4,WHEREGET,NOBCUSE8,BCPREFER,RRCLASS3,RRCOGNT2,RRTREAT,RRATWRK2,RRHCARE4,RRPHYSM2,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE2,_CPRACE2,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_ALTETH3,_DENVST3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_RFMAM22,_MAM5023,_HADCOLN,_CLNSCP1,_HADSIGM,_SGMSCP1,_SGMS101,_RFBLDS5,_STOLDN1,_VIRCOL1,_SBONTI1,_CRCREC2,_SMOKER3,_RFSMOK3,_CURECI2,_YRSSMOK,_PACKDAY,_PACKYRS,_YRSQUIT,_SMOKGRP,_LCSREC,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,1.0,b'02032022',b'02',b'03',b'2022',1100.0,b'2022000001',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,99.0,1.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,80.0,1.0,6.0,1.0,1.0,1.0,2.0,2.0,7.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,2.0,1.0,3.0,2.0,3.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,4.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,1.0,92021.0,2.0,3.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,2.0,11011.0,37.418416,2.0,74.836832,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0,4.0,9.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,1.0,b'02042022',b'02',b'04',b'2022',1100.0,b'2022000002',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,3.0,2.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,3.0,NaN,3.0,4.0,1.0,1.0,2.0,1.0,2.0,2.0,88.0,5.0,NaN,150.0,503.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,4.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,4.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,2.0,NaN,2.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,2.0,1.0,5.0,11011.0,37.418416,1.0,37.418416,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,63.0,160.0,6804.0,2657.0,3.0,2.0,1.0,2.0,3.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0
2,1.0,1.0,b'02022022',b'02',b'02',b'2022',1100.0,b'2022000003',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,1.0,6.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,10.0,NaN,140.0,502.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,2.0,NaN,2.0,7.0,2.0,NaN,2.0,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,2.0,11011.0,37.418416,1.0,37.418416,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,NaN,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,62.0,157.0,6350.0,2561.0,3.0,2.0,1.0,4.0,6.0,1.0,1.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0
3,1.0,1.0,b'02032022',b'02',b'03',b'2022',1100.0,b'2022000004',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,3.0,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,99.0,1.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,1.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,77.0,2.0,140.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,7.0,2.0,1.0,1.0,3.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,3.0,1.0,17.0,999.0,2.0,1.0,2.0,NaN,888.0,NaN,NaN,NaN,1.0,102021.0,1.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,9.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,65.0,165.0,6350.0,2330.0,2.0,1.0,1.0,2.0,9.0,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,56.0,0.1,6.0,NaN,3.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,9.0,9.0,2.0
4,1.0,1.0,b'02022022',b'02',b'02',b'2022',1100.0,b'2022000005',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,2.0,88.0,88.0,7.0,2.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,1.0,5.0,1.0,2.0,NaN,2.0,2.0,5.0,88.0,5.0,2.0,119.0,502.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,1.0,2.0,NaN,203.0,2.0,88.0,2.0,2.0,NaN,1.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,NaN,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,62.0,157.0,5398.0,2177.0,2.0,1.0,1.0,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,1.0,1.000000e+01,1.0,1.400000e+02,1.0,NaN,NaN,2.0

## Selected Attributes

### Response Variables:
1. **DIABETE4**:   (Ever told) (you had) diabetes?  (If Yes -  and respondent is female, ask Was this only when you were pregnant? If Respondent says pre-diabetes or borderline diabetes, use response code 4.)

### Predictor Variables:

#### High Blood Pressure

#### High Cholesterol

#### BMI
5. **_BMI5**: Body Mass Index (BMI)

#### Smoking
6. **SMOKE100**: Have you smoked at least 100 cigarettes in your entire life?   [Note:  5 packs = 100 cigarettes]

#### Other Chronic Health Conditions
7. **CVDSTRK3**: (Ever told) (you had) a stroke.
8. **_MICHD**: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)

#### Physical Activity
9.  **_TOTINDA**: Adults who reported doing physical activity or exercise during the past 30 days other than their regular job

#### Diet


#### Alcohol Consumption
10. **_RFDRHV8**: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week)

#### Health Care
11. **_HLTHPLN**: Adults who had some form of health insurance
12. **MEDCOST1**: Was there a time in the past 12 months when you needed to see a doctor but could not because you could not afford it?

#### Health General and Mental Health
13. **GENHLTH**: Would you say that in general your health is excellent, very good, good, fair, or poor?
14. **MENTHLTH**: Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?
15. **PHYSHLTH**: Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?
16. **DIFFWALK**: Do you have serious difficulty walking or climbing stairs?

#### Demographic Variables
17. **SEXVAR**: Sex of Respondent
18. **_AGEG5YR**: Fourteen-level age category
19. **EDUCA**: What is the highest grade or year of school you completed?
20. **INCOME3**: Is your annual household income from all sources: (If respondent refuses at any income level, code "Refused.")

In [5]:
brfss_df_selected = df[['DIABETE4',
                                         '_BMI5', 
                                         'SMOKE100', 
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_RFDRHV8', 
                                         '_HLTHPLN', 'MEDCOST1', 
                                         'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', 
                                         'SEXVAR', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [6]:
brfss_df_selected.shape

(445132, 17)

In [7]:
brfss_df_selected.head()

,DIABETE4,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV8,_HLTHPLN,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
0,1.0,NaN,2.0,2.0,2.0,2.0,1.0,9.0,2.0,2.0,88.0,88.0,2.0,2.0,13.0,6.0,99.0
1,3.0,2657.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,88.0,88.0,2.0,2.0,13.0,4.0,5.0
2,3.0,2561.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,8.0,6.0,10.0
3,3.0,2330.0,1.0,2.0,2.0,1.0,1.0,9.0,2.0,1.0,88.0,88.0,2.0,2.0,14.0,4.0,77.0
4,3.0,2177.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,4.0,88.0,2.0,2.0,2.0,5.0,5.0,5.0

In [8]:
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(380530, 17)

## Clean

In [9]:
# DIABETE4 = Diabetes Awareness
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({2:0, 3:0, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 9]
brfss_df_selected.DIABETE4.unique()

array([0., 1.])

In [10]:
# #1 _RFHYPE6 = High Blood Pressure Awareness
# #Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
# brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
# brfss_df_selected._RFHYPE6.unique()

In [11]:
# # TOLDHI3 = Cholesterol Awareness
# # Change 2 to 0 because it is No
# # Remove all 7 (dont knows)
# # Remove all 9 (refused)
# brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
# brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
# brfss_df_selected.TOLDHI3.unique()

In [12]:
# # _CHOLCH3 = Cholesterol check within past five years
# # Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# # Remove 9 (don't know/refused)
# brfss_df_selected['_CHOLCH3'] = brfss_df_selected['_CHOLCH3'].replace({3:0,2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._CHOLCH3 != 9]
# brfss_df_selected._CHOLCH3.unique()

In [13]:
# _BMI5 = Body mass index
# BMI are * 100
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([ 27.,  26.,  23.,  22.,  28.,  29.,  33.,  25.,  32.,  45.,  24.,
        37.,  31.,  39.,  34.,  19.,  21.,  35.,  38.,  20.,  46.,  13.,
        30.,  41.,  36.,  17.,  57.,  47.,  43.,  51.,  18.,  44.,  40.,
        50.,  52.,  56.,  42.,  58.,  16.,  49.,  54.,  15.,  92.,  60.,
        53.,  48.,  59.,  62.,  55.,  61.,  77.,  68.,  14.,  86.,  63.,
        66.,  79.,  64.,  73.,  75.,  69.,  71.,  74.,  12.,  85.,  95.,
        67.,  72.,  65.,  76.,  91.,  89.,  70.,  93.,  98.,  80.,  81.,
        82.,  96.,  78.,  83.,  87.,  90.,  88.,  84.,  94.,  97., 100.])

In [14]:
# SMOKE100 = Smoked at Least 100 Cigarettes
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([0., 1.])

In [15]:
# CVDSTRK3 = Chronic Health Conditions
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [16]:
# _MICHD = Ever had CHD or MI
# Coronary Heart Disease (CHD) and Myocardial Infarction (MI)
# Change 2 to 0 because this means they did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [17]:
# _TOTINDA = Leisure Time Physical Activity
# Change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([0., 1.])

In [18]:
# # _FRTLT1A = Consume Fruit 1 or more per day
# # Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_FRTLT1A'] = brfss_df_selected['_FRTLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1A != 9]
# brfss_df_selected._FRTLT1A.unique()

In [19]:
# # _VEGLT1A = Consume Vegetables 1 or more per day
# # Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day 
# # Remove all 9 (don't know/refused)
# brfss_df_selected['_VEGLT1A'] = brfss_df_selected['_VEGLT1A'].replace({2:0})
# brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1A != 9]
# brfss_df_selected._VEGLT1A.unique()

In [20]:
# _RFDRHV8 = Heavy Alcohol Consumption
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# Remove all 9 (don't know/refused)
brfss_df_selected['_RFDRHV8'] = brfss_df_selected['_RFDRHV8'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV8 != 9]
brfss_df_selected._RFDRHV8.unique()

array([0., 1.])

In [21]:
# _HLTHPLN = Have any health insurance
# Change 2 to 0 for no health insurance
# Remove all 9 (don't know/refused)
brfss_df_selected['_HLTHPLN'] = brfss_df_selected['_HLTHPLN'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 9]
brfss_df_selected._HLTHPLN.unique()

array([1., 0.])

In [22]:
# MEDCOST1 = Could Not Afford To See Doctor
# Change 2 to 0 for no
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['MEDCOST1'] = brfss_df_selected['MEDCOST1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 9]
brfss_df_selected.MEDCOST1.unique()

array([0., 1.])

In [23]:
# GENHLTH = General Health
# 1 is Excellent -> 5 is Poor
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([1., 2., 4., 5., 3.])

In [24]:
# MENTHLTH = Number of Days Mental Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad mental health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([ 0.,  3.,  9.,  5., 15., 20., 14., 10., 18.,  1.,  2., 30.,  4.,
        6.,  7., 25.,  8., 27., 21., 12., 16., 13., 28., 29., 26., 17.,
       11., 23., 19., 22., 24.])

In [25]:
# PHYSHLTH = Number of Days Physical Health is Not Good
# It is already in days, scale will be between 0-30
# Change 88 to 0 because it means none (no bad physical health days)
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([ 0.,  2.,  1.,  8.,  5., 30.,  4., 23., 14., 15.,  3., 10.,  7.,
       25.,  6., 21., 20., 29., 16.,  9., 27., 28., 12., 13., 11., 26.,
       17., 24., 18., 19., 22.])

In [26]:
# DIFFWALK = Difficulty Walking or Climbing Stairs
# Change 2 to 0 for no.
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([0., 1.])

In [27]:
# SEXVAR = Respondent Sex
# Men are at higher risk for heart disease
# Change 2 to 0 (female as 0)
brfss_df_selected['SEXVAR'] = brfss_df_selected['SEXVAR'].replace({2:0})
brfss_df_selected.SEXVAR.unique()

array([0., 1.])

In [28]:
# _AGEG5YR = Reported age in five-year age categories
# 5 year increments. It is already ordinal. 1 is 18-24 all the way up to 13 which is 80 and older
# Remove all 14 (don't know or missing)
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([13.,  8.,  5., 11., 10.,  9., 12.,  7.,  6.,  4.,  3.,  2.,  1.])

In [29]:
# EDUCA = Education Level
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove all 9 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([4., 6., 5., 3., 2., 1.])

In [30]:
# INCOME3 = Income Level
# This is already an ordinal variable with 1 being less than $10,000 all the way up to 11 being $200,000 or more
# Remove all 77 (dont knows)
# Remove all 99 (refused)
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected.INCOME3.unique()

array([ 5., 10.,  8.,  7.,  9.,  6.,  2.,  4.,  3.,  1., 11.])

In [31]:
brfss_df_selected.shape

(286769, 17)

In [32]:
brfss_df_selected.head()

,DIABETE4,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_RFDRHV8,_HLTHPLN,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEXVAR,_AGEG5YR,EDUCA,INCOME3
1,0.0,27.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,4.0,5.0
2,0.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,3.0,2.0,0.0,0.0,8.0,6.0,10.0
4,0.0,22.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0,0.0,2.0,0.0,0.0,5.0,5.0,5.0
6,0.0,23.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,13.0,6.0,8.0
7,0.0,28.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,13.0,4.0,7.0

In [33]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    241216
1.0     45553
dtype: int64

In [34]:
#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes', '_RFHYPE6':'HighBP', 'TOLDHI3':'HighChol', '_CHOLCH3':'CholCheck', '_BMI5':'BMI', 'SMOKE100':'Smoker', 'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', '_TOTINDA':'PhysActivity', '_FRTLT1A':'Fruits', '_VEGLT1A':"Veggies", '_RFDRHV8':'HvyAlcoholConsump', '_HLTHPLN':'AnyHealthcare', 'MEDCOST1':'NoDocbcCost', 'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 'SEXVAR':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME3':'Income' })

In [35]:
brfss.head()

,Diabetes,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
1,0.0,27.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,4.0,5.0
2,0.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,3.0,2.0,0.0,0.0,8.0,6.0,10.0
4,0.0,22.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0,0.0,2.0,0.0,0.0,5.0,5.0,5.0
6,0.0,23.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,13.0,6.0,8.0
7,0.0,28.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,13.0,4.0,7.0

In [36]:
brfss.shape

(286769, 17)

In [37]:
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    241216
1.0     45553
dtype: int64

In [38]:
brfss.to_csv('diabetes_BRFSS2022.csv', sep=",", index=False)