In [1]:
import pandas as pd
import numpy as np
import copy

# Read data files

In [2]:
# Read csv files
df2020 = pd.read_csv('diabetes_BRFSS2020.csv')
df2021 = pd.read_csv('diabetes_BRFSS2021.csv')
df2022 = pd.read_csv('diabetes_BRFSS2022.csv')
df2023 = pd.read_csv('diabetes_BRFSS2023.csv')
df2024 = pd.read_csv('diabetes_BRFSS2024.csv')

In [3]:
# Display the first few rows of each dataframe
print("2020 DataFrame:")
display(df2020.head())
print("\n2021 DataFrame:")
display(df2021.head())
print("\n2022 DataFrame:")
display(df2022.head())
print("\n2023 DataFrame:")
display(df2023.head())
print("\n2024 DataFrame:")
display(df2024.head())

2020 DataFrame:

,Diabetes,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,17.0,1.0,0.0,0.0,1.0,0.0,1.0,2.0,30.0,3.0,0.0,0.0,8.0,6.0,1.0
1,1.0,27.0,1.0,0.0,0.0,1.0,0.0,0.0,4.0,30.0,20.0,0.0,1.0,10.0,4.0,5.0
2,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,4.0,6.0
3,0.0,24.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,28.0,1.0,0.0,5.0,6.0,6.0
4,0.0,22.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,15.0,0.0,0.0,11.0,6.0,7.0

2021 DataFrame:

,Diabetes,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,0.0,1.0,1.0,15.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,10.0,20.0,0.0,0.0,11.0,4.0,5.0
1,1.0,1.0,0.0,1.0,28.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,4.0,3.0
2,1.0,1.0,1.0,1.0,33.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,10.0,0.0,0.0,0.0,9.0,4.0,7.0
3,1.0,0.0,1.0,1.0,29.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,5.0,0.0,30.0,1.0,1.0,12.0,3.0,4.0
4,0.0,0.0,0.0,1.0,24.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,13.0,5.0,6.0

2022 DataFrame:

,Diabetes,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,27.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,4.0,5.0
1,0.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,3.0,2.0,0.0,0.0,8.0,6.0,10.0
2,0.0,22.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0,0.0,2.0,0.0,0.0,5.0,5.0,5.0
3,0.0,23.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,13.0,6.0,8.0
4,0.0,28.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,13.0,4.0,7.0

2023 DataFrame:

,Diabetes,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,22.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,4.0,2.0,6.0,1.0,0.0,13.0,4.0,2.0
1,1.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0,0.0,0.0,1.0,0.0,12.0,5.0,7.0
2,0.0,1.0,1.0,1.0,30.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,3.0,2.0,0.0,0.0,9.0,5.0,7.0
3,0.0,1.0,1.0,1.0,33.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,5.0,1.0,0.0,13.0,5.0,6.0
4,1.0,1.0,1.0,1.0,23.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,4.0,7.0

2024 DataFrame:

,Diabetes,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,26.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,13.0,6.0,11.0
1,0.0,25.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,13.0,6.0,6.0
2,0.0,20.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,6.0,5.0,3.0
3,1.0,33.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,0.0,7.0,0.0,1.0,7.0,4.0,9.0
4,0.0,31.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,11.0,5.0,6.0

In [4]:
print(f"\nSize of 2020 DataFrame after removing duplicates: {df2020.shape}")
print(f"Size of 2021 DataFrame after removing duplicates: {df2021.shape}")
print(f"Size of 2022 DataFrame after removing duplicates: {df2022.shape}")
print(f"Size of 2023 DataFrame after removing duplicates: {df2023.shape}")
print(f"Size of 2024 DataFrame after removing duplicates: {df2024.shape}")

Size of 2020 DataFrame after removing duplicates: (276785, 16)
Size of 2021 DataFrame after removing duplicates: (253302, 20)
Size of 2022 DataFrame after removing duplicates: (286769, 17)
Size of 2023 DataFrame after removing duplicates: (261589, 20)
Size of 2024 DataFrame after removing duplicates: (305632, 17)

# Double check for missing or duplicate values

In [5]:
# Check for missing values
for year, df in zip(range(2020, 2025), [df2020, df2021, df2022, df2023, df2024]):
    missing_values = df.isnull().sum()
    if missing_values.any():
        print(f"\nMissing values in {year} DataFrame:")
        print(missing_values[missing_values > 0])
    else:
        print(f"\nNo missing values in {year} DataFrame.")

No missing values in 2020 DataFrame.

No missing values in 2021 DataFrame.

No missing values in 2022 DataFrame.

No missing values in 2023 DataFrame.

No missing values in 2024 DataFrame.

In [6]:
# Check for duplicate rows
for year, df in zip(range(2020, 2025), [df2020, df2021, df2022, df2023, df2024]):
    duplicate_rows = df.duplicated().sum()
    if duplicate_rows > 0:
        print(f"\nNumber of duplicate rows in {year} DataFrame: {duplicate_rows}")
    else:
        print(f"\nNo duplicate rows in {year} DataFrame.")

Number of duplicate rows in 2020 DataFrame: 62157

Number of duplicate rows in 2021 DataFrame: 23190

Number of duplicate rows in 2022 DataFrame: 42364

Number of duplicate rows in 2023 DataFrame: 21911

Number of duplicate rows in 2024 DataFrame: 45528

In [7]:
# Remove duplicate rows
df2020 = df2020.drop_duplicates()
df2021 = df2021.drop_duplicates()
df2022 = df2022.drop_duplicates()
df2023 = df2023.drop_duplicates()
df2024 = df2024.drop_duplicates()

In [8]:
# Check sizes after removing duplicates
print(f"\nSize of 2020 DataFrame after removing duplicates: {df2020.shape}")
print(f"Size of 2021 DataFrame after removing duplicates: {df2021.shape}")
print(f"Size of 2022 DataFrame after removing duplicates: {df2022.shape}")
print(f"Size of 2023 DataFrame after removing duplicates: {df2023.shape}")
print(f"Size of 2024 DataFrame after removing duplicates: {df2024.shape}")

Size of 2020 DataFrame after removing duplicates: (214628, 16)
Size of 2021 DataFrame after removing duplicates: (230112, 20)
Size of 2022 DataFrame after removing duplicates: (244405, 17)
Size of 2023 DataFrame after removing duplicates: (239678, 20)
Size of 2024 DataFrame after removing duplicates: (260104, 17)

# Remove outliers using IQR

In [9]:
# Remove outliers using IQR
def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df >= lower_bound) & (df <= upper_bound)]

numeric_cols = ['BMI', 'MentHlth', 'PhysHlth']
for year, df in zip(range(2020, 2025), [df2020, df2021, df2022, df2023, df2024]):
    for col in numeric_cols:
        df = remove_outliers_iqr(df, col)
    print(f"\nSize of {year} DataFrame after removing outliers: {df.shape}")

Size of 2020 DataFrame after removing outliers: (214628, 16)

Size of 2021 DataFrame after removing outliers: (230112, 20)

Size of 2022 DataFrame after removing outliers: (244405, 17)

Size of 2023 DataFrame after removing outliers: (239678, 20)

Size of 2024 DataFrame after removing outliers: (260104, 17)

# Saving cleaned data files

In [10]:
# Save cleaned data files
df2020.to_csv('cleaned_diabetes_BRFSS2020.csv', index=False)
df2021.to_csv('cleaned_diabetes_BRFSS2021.csv', index=False)
df2022.to_csv('cleaned_diabetes_BRFSS2022.csv', index=False)
df2023.to_csv('cleaned_diabetes_BRFSS2023.csv', index=False)
df2024.to_csv('cleaned_diabetes_BRFSS2024.csv', index=False)

In [12]:
# Merge and save 2021 + 2023 cleaned data for training
merged_df = pd.concat([df2021, df2023], ignore_index=True)

# Triple check for duplicates in merged data
duplicate_rows_merged = merged_df.duplicated().sum()
if duplicate_rows_merged > 0:
    print(f"\nNumber of duplicate rows in merged DataFrame: {duplicate_rows_merged}")
    merged_df = merged_df.drop_duplicates()
    print(f"Size of merged DataFrame after removing duplicates: {merged_df.shape}")
else:
    print("\nNo duplicate rows in merged DataFrame.")

# Save merged data
merged_df.to_csv('training_data.csv', index=False)

Number of duplicate rows in merged DataFrame: 19811
Size of merged DataFrame after removing duplicates: (449979, 20)